WIP : news teams fields infos

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,108 +19,169 @@
 # See the Licence for the specific language governing permissions and
 # limitations under the Licence.
 
+WHITE="\033[1;97;49m"
+
 # Init setup env & load pre-existing KCLIE env
 export SETUP_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 if [ -e ${SETUP_PATH}/env ] ; then
-    source ${SETUP_PATH}/env
+  source ${SETUP_PATH}/env
 fi
 
 ####
 # INTERACTIVE PART
 ####
-
-# Team Name
-if [ "x${KCLIE_TEAM_NAME}" = "x" ] ; then
-    echo
-    read -p 'Name of the hosting team : ' SETUP_TEAM_NAME
-fi
+echo -e "\n\t\033[1;34;49mKimengumi Command Line Interface Environnement\033[0m\n"
 
 # Color picker
-if [ "x${KCLIE_TEAM_COLOR}" = "x" ] || [ "x${KCLIE_HOST_COLOR}" = "x" ] ; then
-    echo
-    echo "Color code picker :"
-    echo
-    BACKGS=(049 040 100 047 107 041 101 042 102 043 103 044 104 045 105 046 106)
-    FOREGS=( 30  90  37  97  39  31  91  32  92  33  93  34  94  35  95  36  96)
-    for FID in "${!FOREGS[@]}"; do
-        for BID in "${!BACKGS[@]}"; do
-            echo -en "\033[${BACKGS[$BID]};${FOREGS[$FID]}m${FOREGS[$FID]}${BACKGS[$BID]}\033[0m "
-        done
-        echo
+if [ "x${KCLIE_TENANT_COLOR}" = "x" ] || \
+[ "x${KCLIE_TEAM_APP_COLOR}" = "x" ] || \
+[ "x${KCLIE_TEAM_ADMIN_COLOR}" = "x" ] || \
+[ "x${KCLIE_TEAM_HOSTING_COLOR}" = "x" ]|| \
+[ "x${KCLIE_HOSTNAME_COLOR}" = "x" ] ; then
+
+  echo "The following information asked bellow will be display in the KCLIE motd banner."
+  echo "All informations are optional\n"
+
+  echo -e "\t\tColor/Format Picker"
+
+  #Best Of
+  for PFOR in `seq 30 37` ; do
+    VIVID=`expr $PFOR + 60`
+    for PSET in 3 4 1 7; do
+      echo -ne " \033[${PSET};${PFOR};049m${PSET}${PFOR}049\033[0m"
+      echo -ne " \033[${PSET};${VIVID};049m${PSET}${VIVID}049\033[0m"
     done
+    echo
+  done
+
+  #Full
+  #for PSET in  1 3 4 7 ; do
+  #  for PFOR in `seq 30 37` `seq 90 97` ; do
+  #    for PBAC in 049 `seq -w 040 047` `seq -w 100 107` ; do
+  #      echo -ne " \033[${PSET};${PFOR};${PBAC}""m${PSET}${PFOR}${PBAC}\033[0m"
+  #    done
+  #    echo
+  #  done
+  #done
+
 fi
 
-# Team Color
-if [ "x${KCLIE_TEAM_COLOR}" = "x" ]  ; then
-    echo
-    read -p "Color code for Team : " SETUP_TEAM_COLOR
+# Tenant
+if [ "x${KCLIE_TENANT_NAME}" = "x" ] || [ "x${KCLIE_TENANT_COLOR}" = "x" ] ; then
+  echo
+  echo -e "${WHITE}Tenant\033[0m (final customer / payer)"
+  read -p 'Name : ' SETUP_TENANT_NAME
+  read -p 'Color/Format code (use picker above): ' SETUP_TENANT_COLOR
+fi
+
+# Development team
+if [ "x${KCLIE_TEAM_APP_NAME}" = "x" ] || [ "x${KCLIE_TEAM_APP_COLOR}" = "x" ] ; then
+  echo
+  echo -e "${WHITE}3rd Application Management Team\033[0m"
+  read -p 'Name : ' SETUP_TEAM_APP_NAME
+  read -p 'Color/Format code (use picker above) : ' SETUP_TEAM_APP_COLOR
+fi
+
+# Hosting management team
+if [ "x${KCLIE_TEAM_ADMIN_NAME}" = "x" ] || [ "x${KCLIE_TEAM_ADMIN_COLOR}" = "x" ] ; then
+  echo
+  echo -e "${WHITE}System/Network Administrators \033[0m (hosting management team)"
+  read -p 'Name : ' SETUP_TEAM_ADMIN_NAME
+  read -p 'Color/Format code (use picker above) : ' SETUP_TEAM_ADMIN_COLOR
+fi
+
+# Physical hosting team
+if [ "x${KCLIE_TEAM_HOSTING_NAME}" = "x" ] || [ "x${KCLIE_TEAM_HOSTING_COLOR}" = "x" ] ; then
+  echo
+  echo -e "${WHITE}Hosting Team\033[0m (hardware/physical)"
+  read -p 'Name : ' SETUP_TEAM_HOSTING_NAME
+  read -p 'Color/Format code (use picker above) : ' SETUP_TEAM_HOSTING_COLOR
 fi
 
 # Host Color
-if [ "x${KCLIE_HOST_COLOR}" = "x" ] ; then
-    echo
-    read -p "Color code for Host : " SETUP_HOST_COLOR
+if [ "x${KCLIE_HOSTNAME_COLOR}" = "x" ] ; then
+  echo
+  echo -e "${WHITE}Hostname\033[0m"
+  read -p "Color/Format code (use picker above) : " SETUP_HOSTNAME_COLOR
 fi
 
 # Oh My Zsh
 if [ -e /usr/bin/zsh ] && [ ! -e ${SETUP_PATH}/vendor/oh-my-zsh/oh-my-zsh.sh ] ; then
-    echo
-    read -p "Do You want to install 'Oh My Zsh' ? [y/N] : " SETUP_OHMYZSH
+  echo
+  read -p "Do You want to install 'Oh My Zsh' ? [y/N] : " SETUP_OHMYZSH
 fi
 
 if [ "$(id -u)" != "0" ] ; then
-    echo
-    echo "The configuration script is not running as root."
-    read -p "Do you want to configure KCLIE for the running user only ? [y/N] : " SETUP_USERMODE
-    if [ "x${SETUP_USERMODE}" != "xy" ] ; then
-        echo "To install KCLIE globaly to your systemn, please run the configure script as root"
-        exit
-    fi
+  echo
+  echo "The configuration script is not running as root."
+  read -p "Do you want to configure KCLIE for the running user only ? [y/N] : " SETUP_USERMODE
+  if [ "x${SETUP_USERMODE}" != "xy" ] ; then
+    echo "To install KCLIE globaly to your systemn, please run the configure script as root"
+    exit
+  fi
 fi
 
 ####
 # AUTOMATED PART
 ####
+echo -e "\n${WHITE}=== Setup / Upgrade ===\033[0m"
+echo -e "KCLIE directory is : ${SETUP_PATH}"
 
-echo
-echo "=== Setup / Upgrade ==="
-echo "KCLIE directory is : ${SETUP_PATH}"
-
-echo "Configuring KCLIE ..."
 # Init env file
+echo -e "${WHITE}Configuring KCLIE ...\033[0m"
 if [ ! -e ${SETUP_PATH}/env ] ; then
-    echo '#
-    # Kimengumi Command Line Interface Environnement
-    #
-    # Host configuration file
-    #
-    # This file must only contain KEY=VALUE lines.
-    # Please do not use advanced shell script constructs!
-    #
-    ' > ${SETUP_PATH}/env || (echo "ERROR : can't write env file" ; exit)
-    # Update path if moved
+  echo '#
+  # Kimengumi Command Line Interface Environnement
+  #
+  # Host configuration file
+  #
+  # This file must only contain KEY=VALUE lines.
+  # Please do not use advanced shell script constructs!
+  #
+  ' > ${SETUP_PATH}/env || (echo "ERROR : can't write env file" ; exit)
+  # Update path if moved
 fi
 if [ "x${SETUP_PATH}" != "x${KCLIE_PATH}" ] ; then
-    echo "KCLIE_PATH=\"${SETUP_PATH}\"" >> ${SETUP_PATH}/env
+  echo "KCLIE_PATH=\"${SETUP_PATH}\"" >> ${SETUP_PATH}/env
 fi
-if [ "x${SETUP_TEAM_NAME}" != "x" ] ; then
-    echo "KCLIE_TEAM_NAME='${SETUP_TEAM_NAME}'" >> ${SETUP_PATH}/env
+if [ "x${SETUP_TENANT_NAME}" != "x" ] ; then
+  echo "KCLIE_TENANT_NAME='${SETUP_TENANT_NAME}'" >> ${SETUP_PATH}/env
 fi
-if [ "x${SETUP_TEAM_COLOR}" != "x" ] ; then
-    echo "KCLIE_TEAM_COLOR='\033[`echo ${SETUP_TEAM_COLOR} | cut -c 1-2`;`echo ${SETUP_TEAM_COLOR} | cut -c 3-5`m'" >> ${SETUP_PATH}/env
+if [ "x${SETUP_TENANT_COLOR}" != "x" ] ; then
+  echo ${SETUP_TENANT_COLOR} | awk '{printf "KCLIE_TENANT_COLOR=\"\\033[%1d;%2d;%3dm\"\n",substr($0,0,1),substr($0,1,2),substr($0,3,3)}' >> ${SETUP_PATH}/env
 fi
-if [ "x${SETUP_HOST_COLOR}" != "x" ] ; then
-    echo "KCLIE_HOST_COLOR='\033[`echo ${SETUP_HOST_COLOR} | cut -c 1-2`;`echo ${SETUP_HOST_COLOR} | cut -c 3-5`m'" >> ${SETUP_PATH}/env
+if [ "x${SETUP_TEAM_APP_NAME}" != "x" ] ; then
+  echo "KCLIE_TEAM_APP_NAME='${SETUP_TEAM_APP_NAME}'" >> ${SETUP_PATH}/env
+fi
+if [ "x${SETUP_TEAM_APP_COLOR}" != "x" ] ; then
+  echo ${SETUP_TEAM_APP_COLOR} | awk '{printf "KCLIE_TEAM_APP_COLOR=\"\\033[%1d;%2d;%3dm\"\n",substr($0,0,1),substr($0,1,2),substr($0,3,3)}' >> ${SETUP_PATH}/env
+fi
+if [ "x${SETUP_TEAM_ADMIN_NAME}" != "x" ] ; then
+  echo "KCLIE_TEAM_ADMIN_NAME='${SETUP_TEAM_ADMIN_NAME}'" >> ${SETUP_PATH}/env
+fi
+if [ "x${SETUP_TEAM_ADMIN_COLOR}" != "x" ] ; then
+  echo ${SETUP_TEAM_ADMIN_COLOR} | awk '{printf "KCLIE_TEAM_ADMIN_COLOR=\"\\033[%1d;%2d;%3dm\"\n",substr($0,0,1),substr($0,1,2),substr($0,3,3)}' >> ${SETUP_PATH}/env
+fi
+if [ "x${SETUP_TEAM_HOSTING_NAME}" != "x" ] ; then
+  echo "KCLIE_TEAM_HOSTING_NAME='${SETUP_TEAM_HOSTING_NAME}'" >> ${SETUP_PATH}/env
+fi
+if [ "x${SETUP_TEAM_HOSTING_COLOR}" != "x" ] ; then
+  echo ${SETUP_TEAM_HOSTING_COLOR} | awk '{printf "KCLIE_TEAM_HOSTING_COLOR=\"\\033[%1d;%2d;%3dm\"\n",substr($0,0,1),substr($0,1,2),substr($0,3,3)}' >> ${SETUP_PATH}/env
+fi
+if [ "x${SETUP_HOSTNAME_COLOR}" != "x" ] ; then
+  echo ${SETUP_HOSTNAME_COLOR} | awk '{printf "KCLIE_HOSTNAME_COLOR=\"\\033[%1d;%2d;%3dm\"\n",substr($0,0,1),substr($0,1,2),substr($0,3,3)}' >> ${SETUP_PATH}/env
 fi
 source ${SETUP_PATH}/env
 
 # Oh My ZSH
 if [ -e ${SETUP_PATH}/vendor/oh-my-zsh/.git ] ; then
-    echo "Updating Oh My Zsh ..."
-    (cd ${SETUP_PATH}/vendor/oh-my-zsh && git pull)
+  echo -e "${WHITE}Updating Oh My Zsh ...\033[0m"
+  echo ""
+  (cd ${SETUP_PATH}/vendor/oh-my-zsh && git pull)
 elif [ "x${SETUP_OHMYZSH}" = "xy" ] ; then
-    echo "Installing Oh My Zsh ..."
-    (mkdir -p ${SETUP_PATH}/vendor/oh-my-zsh && cd ${SETUP_PATH}/vendor/oh-my-zsh && git clone https://github.com/robbyrussell/oh-my-zsh.git .)
+  echo -e "${WHITE}Updating Oh My Zsh ...\033[0m"
+  echo "Installing Oh My Zsh ..."
+  (mkdir -p ${SETUP_PATH}/vendor/oh-my-zsh && cd ${SETUP_PATH}/vendor/oh-my-zsh && git clone https://github.com/robbyrussell/oh-my-zsh.git .)
 fi
 
 #
@@ -128,81 +189,82 @@ fi
 #
 if [ "x${SETUP_USERMODE}" = "xy" ] ; then
 
-    echo "Applying user shells customizations ...".
-    # PROFILE
-    touch ~/.bash_profile
-    for RC_BASH in ~/.profile ~/.bash_profile ~/.zshrc ; do
-        if [ -w ${RC_BASH} ] && ! grep -q "\. ${SETUP_PATH}/env" ${RC_BASH} ; then
-            echo ""  >> ${RC_BASH}
-            echo "# Kimengumi Command Line Interface Environnement"  >> ${RC_BASH}
-            echo "set -a"  >> ${RC_BASH}
-            echo ". ${SETUP_PATH}/env" >> ${RC_BASH}
-            echo "set +a"  >> ${RC_BASH}
-            echo '. ${KCLIE_PATH}/etc/profile' >> ${RC_BASH}
-            echo 'if [ ! -z "$PS1" ] ; then ${KCLIE_PATH}/bin/motd ; fi' >> ${RC_BASH}
-        fi
-    done
-    # ZSH SPECIFIC
-    if [ -w ~/.zshrc ] && ! grep -q '${KCLIE_PATH}/etc/zsh/zshrc' ~/.zshrc ; then
-        echo '. ${KCLIE_PATH}/etc/zsh/zshrc' >> ~/.zshrc
-        echo '. ${KCLIE_PATH}/etc/zsh/zlogout' >> ~/.zlogout
+  echo -e "${WHITE}Applying user shells customizations ...\033[0m"
+  # PROFILE
+  touch ~/.bash_profile
+  for RC_BASH in ~/.profile ~/.bash_profile ~/.zshrc ; do
+    if [ -w ${RC_BASH} ] && ! grep -q "\. ${SETUP_PATH}/env" ${RC_BASH} ; then
+      echo ""  >> ${RC_BASH}
+      echo "# Kimengumi Command Line Interface Environnement"  >> ${RC_BASH}
+      echo "set -a"  >> ${RC_BASH}
+      echo ". ${SETUP_PATH}/env" >> ${RC_BASH}
+      echo "set +a"  >> ${RC_BASH}
+      echo '. ${KCLIE_PATH}/etc/profile' >> ${RC_BASH}
+      echo 'if [ ! -z "$PS1" ] ; then ${KCLIE_PATH}/bin/motd ; fi' >> ${RC_BASH}
     fi
-    # TERMINAL CONF
-    for RC_SKEL in .minttyrc .dircolors ; do
-        if [ ! -e ~/${RC_SKEL} ] ; then
-            cat ${SETUP_PATH}/etc/skel/${RC_SKEL} > ~/${RC_SKEL}
-        fi
-    done
+  done
+  # ZSH SPECIFIC
+  if [ -w ~/.zshrc ] && ! grep -q '${KCLIE_PATH}/etc/zsh/zshrc' ~/.zshrc ; then
+    echo '. ${KCLIE_PATH}/etc/zsh/zshrc' >> ~/.zshrc
+    echo '. ${KCLIE_PATH}/etc/zsh/zlogout' >> ~/.zlogout
+  fi
+  # TERMINAL CONF
+  for RC_SKEL in .minttyrc .dircolors ; do
+    if [ ! -e ~/${RC_SKEL} ] ; then
+      cat ${SETUP_PATH}/etc/skel/${RC_SKEL} > ~/${RC_SKEL}
+    fi
+  done
 
-    echo done ; exit
+  echo done ; exit
 fi
 
 #
 # SETUP IN GLOBAL MODE
 #
 
-echo "Applying shells customizations ...".
+echo -e "${WHITE}Applying shells customizations ...\033[0m"
 # PROFILE
 for RC_BASH in /etc/bash.bashrc /etc/bashrc /etc/zsh/zshrc /etc/zshrc ; do
-    if [ -w ${RC_BASH} ] && ! grep -q "\. ${SETUP_PATH}/etc/profile" ${RC_BASH} ; then
-        echo ""  >> ${RC_BASH}
-        echo "# Kimengumi Command Line Interface Environnement"  >> ${RC_BASH}
-        echo "set -a"  >> ${RC_BASH}
-        echo ". ${SETUP_PATH}/env" >> ${RC_BASH}
-        echo "set +a"  >> ${RC_BASH}
-        echo ". ${SETUP_PATH}/etc/profile" >> ${RC_BASH}
-    fi
+  if [ -w ${RC_BASH} ] && ! grep -q "\. ${SETUP_PATH}/etc/profile" ${RC_BASH} ; then
+    echo ""  >> ${RC_BASH}
+    echo "# Kimengumi Command Line Interface Environnement"  >> ${RC_BASH}
+    echo "set -a"  >> ${RC_BASH}
+    echo ". ${SETUP_PATH}/env" >> ${RC_BASH}
+    echo "set +a"  >> ${RC_BASH}
+    echo ". ${SETUP_PATH}/etc/profile" >> ${RC_BASH}
+  fi
 done
 # ZSH SPECIFIC
 for ETC_ZSH_DIR in /etc/zsh/ /etc/ ; do
-    if [ -w ${ETC_ZSH_DIR}/zshrc ] && ! grep -q "\. ${SETUP_PATH}/etc/zsh/zshrc" ${ETC_ZSH_DIR}/zshrc ; then
-        echo ". ${SETUP_PATH}/etc/zsh/zshrc" >> ${ETC_ZSH_DIR}/zshrc
-        echo ". ${SETUP_PATH}/etc/zsh/zlogout" >> ${ETC_ZSH_DIR}/zlogout
-    fi
+  if [ -w ${ETC_ZSH_DIR}/zshrc ] && ! grep -q "\. ${SETUP_PATH}/etc/zsh/zshrc" ${ETC_ZSH_DIR}/zshrc ; then
+    echo ". ${SETUP_PATH}/etc/zsh/zshrc" >> ${ETC_ZSH_DIR}/zshrc
+    echo ". ${SETUP_PATH}/etc/zsh/zlogout" >> ${ETC_ZSH_DIR}/zlogout
+  fi
 
 done
 
-echo "Installing welcome banner ..."
+echo -e "${WHITE}Installing welcome banner ...\033[0m"
 # Motd
 if [ -w /etc/update-motd.d ] && [ ! -d /etc/update-motd.d.dist ] ; then
-    # Ubuntu
-    mv /etc/update-motd.d /etc/update-motd.d.dist
-    mkdir /etc/update-motd.d
-    ln -s  ${SETUP_PATH}/bin/motd /etc/update-motd.d/0000-kclie
+  # Ubuntu
+  mv /etc/update-motd.d /etc/update-motd.d.dist
+  mkdir /etc/update-motd.d
+  ln -s  ${SETUP_PATH}/bin/motd /etc/update-motd.d/0000-kclie
 elif [ -w /etc/motd ] ; then
-    # Other
-    echo -e "#!/bin/bash
-    ${SETUP_PATH}/bin/motd > /etc/motd 2>&1" > /etc/cron.hourly/kcliebanner
-    chmod 755 /etc/cron.hourly/kcliebanner
-    /etc/cron.hourly/kcliebanner
+  # Other
+  echo -e "#!/bin/bash
+  ${SETUP_PATH}/bin/motd > /etc/motd 2>&1" > /etc/cron.hourly/kcliebanner
+  chmod 755 /etc/cron.hourly/kcliebanner
+  /etc/cron.hourly/kcliebanner
 fi
 
 # Ubuntu LightDm config
 if [ -w '/usr/share/lightdm/lightdm.conf.d' ] ; then
-    echo "Applying LightDM customization ..."
-    echo '[SeatDefaults]
-    greeter-hide-users=true
-    greeter-show-manual-login=true' > /usr/share/lightdm/lightdm.conf.d/99-kclie.conf
+  echo -e "${WHITE}Applying LightDM customization ...\033[0m"
+
+  echo '[SeatDefaults]
+  greeter-hide-users=true
+  greeter-show-manual-login=true' > /usr/share/lightdm/lightdm.conf.d/99-kclie.conf
 fi
 
-echo done
+echo -e "\033[1m\033[92;049mDone\033[0m"
